import React from "react";
import { Shield, Globe, Activity } from "lucide-react";

export const NAV_LINKS = [
  { name: "Verticals", href: "#portfolio" },
  { name: "About", href: "#about" },
  { name: "Strategy", href: "#strategy" },
  { name: "Partnerships", href: "#partnerships" },
  { name: "Join", href: "#join" },
];

export const CONTENT = {
  brand: "Unified Asset Bureau",
  heroTitle: "Unified Asset Bureau",
  heroSubtitle: "A holding company structuring and controlling a multi-sector portfolio across real estate, operations, and technology.",
  heroSupport: "Built for control. Designed for scale.",
  exploreBtn: "Explore Verticals",
  partnerBtn: "Partner With Us",
  aboutTag: "Identity",
  aboutPara1: "Unified Asset Bureau is a U.S.-based holding company established to structure, manage, and scale a diversified portfolio of businesses across Saudi Arabia.",
  aboutPara2: "The group operates across real estate, leasehold models, hospitality operations, and technology platforms. The company is built on active control, integrating operations, financial systems, and asset strategies under one unified structure.",
  methodTag: "Methodology",
  strategyTitle: "Our Approach",
  portfolioTag: "Operational Layer",
  portfolioTitle: "Operating Verticals",
  portfolioDesc: "A structured set of operating platforms designed to build, control, and scale asset-backed businesses across multiple sectors.",
  explorePlatformBtn: "Explore Platform",
  inquiriesTag: "Inquiries",
  partnershipsTitle: "Partnerships",
  partnershipsDesc: "We collaborate with operators, investors, and institutions to build and scale asset-backed ventures.",
  contactBtn: "Contact Us",
  footerCaption: "Structuring and operating high-conviction assets for extreme longevity and scale.",
  jurisdictionTag: "Jurisdiction",
  intelligenceTag: "Intelligence",
  locNY: "New York, United States",
  locRIY: "Riyadh, Saudi Arabia",
  locDUB: "Dubai, UAE",
  intel1: "Structure Overview",
  intel2: "Regulatory Audit",
  intel3: "Asset Strategy",
  copyright: "© 2026 Unified Asset Bureau. Operational Excellence.",
  backHome: "Back to Home",
  main: "Main",
  home: "Home",
  tierLabel: "Tier",
  structureTitle: "Structure Overview",
  structureSub: "Institutional control via a multi-layered governance system ensuring regulatory compliance.",
  tier1Title: "Parent Bureau (U.S.)",
  tier1Desc: "The primary governing layer holding global equity and directing institutional philosophy across all jurisdictions.",
  tier2Title: "Regional Portfolios",
  tier2Desc: "Geographically optimized hubs (KSA & GCC) managing asset deployment and regional regulatory alignment.",
  tier3Title: "Operational Entities",
  tier3Desc: "Wholly-owned subsidiaries executing sector-specific operations under a unified administrative framework.",
  govProtocol: "Internal Governance Protocol",
  centralSystems: "Centralized Systems",
  unifiedControls: "Unified treasury, legal, and operational controls across the entire group.",
  regAuditTitle: "Regulatory Audit",
  regAuditSub: "Strict adherence to international and local legal standards across all operational jurisdictions.",
  complianceTitle: "Compliance",
  complianceDesc: "Continuous monitoring of U.S. SEC standards and KSA MISA regulations to ensure perpetual entity readiness.",
  legalFrameworkTitle: "Legal Framework",
  legalFrameworkDesc: "Proprietary legal structures designed for optimal cross-border capital flow and intellectual property protection.",
  reportingTitle: "Reporting",
  reportingDesc: "Automated, transparent auditing systems providing real-time oversight for institutional partners.",
  globalStandard: "Global Standard",
  transparencyQuote: "\"We operate at the highest tier of institutional transparency, ensuring our governance exceeds regional requirements.\"",
  assetStrategyTitle: "Asset Strategy",
  assetStrategySub: "Capital deployment into high-conviction assets ensuring sustainability and true generational growth.",
  investPhilosophy: "Investment Philosophy",
  philosophy1: "01. Asset-Backed Security",
  philosophy2: "02. Operational Consolidation",
  philosophy3: "03. Vertical Integration",
  philosophy4: "04. Generational Time Horizons",
  capDeploymentTitle: "Capital Deployment",
  capDeploymentDesc: "We focus on businesses where the underlying asset provides a baseline of terminal value. This includes prime real estate and core technology infrastructure.",
  riskMgmtTitle: "Risk Management",
  riskMgmtDesc: "Aggressive growth is tempered by institutional-grade risk controls. Diversification across sectors—real estate to tech—is intentional and structured.",
  partnerPageTitle: "Partnership Inquiry",
  partnerPageSub: "Initiate high-conviction collaboration. Provide institutional context for your proposal.",
  formEntity: "Entity Name",
  formContact: "Primary Representative",
  formEmail: "Institutional Email",
  formSector: "Sector of Interest",
  formMessage: "Strategic Intent / Proposal",
  formSubmit: "Submit Inquiry",
  formSuccess: "Inquiry received. Our office will review for strategic alignment.",
  joinTag: "System Entry",
  joinTitle: "Join",
  joinIntro: "This is not a typical hiring process.",
  joinIntroSupport: "We work with people who can take ownership, build, and operate.",
  joinEmploymentTitle: "Join as an Operator",
  joinEmploymentSubtitle: "Institutional Path 01",
  joinEmploymentText: "This is not a job.\n\nYou will be expected to make decisions,\ntake responsibility,\nand deliver outcomes.",
  joinEmploymentCTA: "Apply",
  joinTrainingTitle: "Training Program",
  joinTrainingSubtitle: "Institutional Path 02",
  joinTrainingText: "This is not an internship.\n\nYou will work on real systems,\nreal companies,\nand real responsibilities.",
  joinTrainingCTA: "Apply",
  joinFormTitle: "System Application",
  operatorFormTitle: "Operator Application",
  trainingFormTitle: "Training Application",
  operatorFormStatement: "This is not a job.",
  operatorFormExpectations: ["make decisions", "take ownership", "deliver outcomes"],
  trainingFormStatement: "This is not a typical internship.",
  trainingFormExpectations: ["work on real systems", "support real operations", "learn through execution"],
  joinFormSub: "Provide your professional profile for internal review.",
  formName: "Full Name",
  formPhone: "Phone Number",
  formRole: "Target Role / Intent",
  formResume: "LinkedIn Profile / CV Link",
  formWhatCanYouBuild: "What can you build?",
  formExecutionExample: "Example of something you executed",
  formWhyJoin: "Why do you want to join?",
  formWhatToLearn: "What do you want to learn?",
};

export const VERTICALS = [
  {
    name: "Real Estate",
    description: "Asset acquisition, development, and portfolio structuring across key urban markets.",
    category: "Vertical 01",
  },
  {
    name: "Leasehold",
    description: "Long-term asset utilization models enabling access, control, and scalable real estate operations.",
    category: "Vertical 02",
  },
  {
    name: "Hospitality",
    description: "Operational systems and asset-backed models for short-term and serviced accommodation.",
    category: "Vertical 03",
  },
  {
    name: "Services",
    description: "Integrated support services enabling operational efficiency across managed assets.",
    category: "Vertical 04",
  },
  {
    name: "Technology",
    description: "Digital platforms powering asset management, operations, and financial tracking.",
    category: "Vertical 05",
  },
  {
    name: "Infrastructure",
    description: "Foundational systems supporting asset performance, scalability, and long-term value creation.",
    category: "Vertical 06",
  },
];

export const STRATEGY = [
  {
    title: "Control",
    description: "We maintain full operational and structural control across our portfolio to ensure strategic alignment.",
    icon: <Shield className="w-5 h-5" />,
  },
  {
    title: "Integration",
    description: "Connecting real estate, operations, and technology into unified proprietary systems.",
    icon: <Globe className="w-5 h-5" />,
  },
  {
    title: "Asset-Driven Growth",
    description: "Focusing strictly on scalable, asset-backed business models with generational durability.",
    icon: <Activity className="w-5 h-5" />,
  },
];
